name: jenaiz.com - Smell the Code
markdown: redcarpet
highlighter: true
description: by Jesús Navarrete
url: http://jenaiz.com

#permalink: /post/:title
permalink: /:year/:month/:title
relative_permalinks: true
